export const GET_ALL_USERS_PENDING = "GET_ALL_USERS_PENDING";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const GET_USER_DETAILS = "GET_USER_DETAILS";

export const DISABLE_MODAL = "DISABLE_MODAL";
